import json
import os

def convert_json_to_netscape(json_path, output_path):
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    cookies = []
    if isinstance(data, list):
        cookies = data
    elif isinstance(data, dict) and 'cookies' in data:
        cookies = data['cookies']
    else:
        print("Unknown JSON cookie format")
        return

    with open(output_path, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by Antigravity. Do not edit.\n\n")
        
        for c in cookies:
            # Netscape format: domain, include_subdomains, path, secure, expiry, name, value
            domain = c.get('domain', '')
            include_subdomains = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = c.get('path', '/')
            secure = 'TRUE' if c.get('secure', False) else 'FALSE'
            expiry = int(c.get('expirationDate', 0))
            name = c.get('name', '')
            value = c.get('value', '')
            
            f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

if __name__ == "__main__":
    json_file = "www.youtube.com_10-02-2026.json"
    output_file = "cookies.txt"
    if os.path.exists(json_file):
        convert_json_to_netscape(json_file, output_file)
        print(f"Successfully converted {json_file} to {output_file}")
    else:
        print(f"Error: {json_file} not found")
